export const users: UserDto[] = [
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Ohiva Rhye',
    username: 'olivia',
    phone: '+250 783 213 443',
    email: 'oliva@unirilledul.com',
    institution: 'RDB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Phoenix Baker',
    username: 'phoenix',
    phone: '+250 783 213 443',
    email: 'phoenix@unirilledul.com',
    institution: 'RBA',
    role: 'Admin',
    status: 'inactive',
  },
  {
    name: 'Lana Steiner',
    username: 'lana',
    phone: '+250 783 213 443',
    email: 'lana@unirilledul.com',
    institution: 'RTB',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Demi Wilkinson',
    username: 'demi',
    phone: '+250 783 213 443',
    email: 'demi@unirilledul.com',
    institution: 'RCA',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Candice Wu',
    username: 'candice',
    phone: '+250 783 213 443',
    email: 'candice@unirilledul.com',
    institution: 'NESA',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Natal Craig',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'natal@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Drew Cano',
    username: 'drew',
    phone: '+250 783 213 443',
    email: 'drew@unirilledul.com',
    institution: 'MINICT',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Orlando Diggs',
    username: 'orlando',
    phone: '+250 783 213 443',
    email: 'orlando@unirilledul.com',
    institution: 'Irembo',
    role: 'Admin',
    status: 'active',
  },
  {
    name: 'Andi Lane',
    username: 'natal',
    phone: '+250 783 213 443',
    email: 'andi@unirilledul.com',
    institution: 'QT Global',
    role: 'Manager',
    status: 'active',
  },
  {
    name: 'Kate Morrison',
    username: 'kate',
    phone: '+250 783 213 443',
    email: 'kate@unirilledul.com',
    institution: 'REB',
    role: 'Admin',
    status: 'active',
  },
];











